[package]
name = "rust2go"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasi = "0.11.0+wasi-snapshot-preview1"
clap = { version = "3.0.13", features = ["derive"] }
fixed = "1.7.0"